stages:
  - build
  - deploy

dev_image-build:
  only:
   - develop
  stage: build
  tags:
    - dev
  script:
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 895812715899.dkr.ecr.eu-central-1.amazonaws.com
    - docker build -t 895812715899.dkr.ecr.eu-central-1.amazonaws.com/bitocol-eth-parser:$CI_COMMIT_BRANCH$CI_PIPELINE_IID .
    - docker push 895812715899.dkr.ecr.eu-central-1.amazonaws.com/bitocol-eth-parser:$CI_COMMIT_BRANCH$CI_PIPELINE_IID

prod_image-build:
  only:
   - master
  stage: build
  tags:
    - builder
  script:
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 895812715899.dkr.ecr.eu-central-1.amazonaws.com
    - docker build -t 895812715899.dkr.ecr.eu-central-1.amazonaws.com/bitocol-eth-parser:$CI_COMMIT_BRANCH$CI_PIPELINE_IID .
    - docker push 895812715899.dkr.ecr.eu-central-1.amazonaws.com/bitocol-eth-parser:$CI_COMMIT_BRANCH$CI_PIPELINE_IID

dev_deploy:
   only:
     - develop
   stage: deploy
   tags:
     - dev
   script:
     - aws ecr get-login-password --region eu-central-1 | sudo docker login --username AWS --password-stdin 895812715899.dkr.ecr.eu-central-1.amazonaws.com
     - sudo docker stop eth-parser && sudo docker rm eth-parser
     - sudo docker run --name eth-parser -d 895812715899.dkr.ecr.eu-central-1.amazonaws.com/bitocol-eth-parser:$CI_COMMIT_BRANCH$CI_PIPELINE_IID
     
prod_deploy:
   only:
     - master
   stage: deploy
   tags:
     - builder
   script:
     - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 895812715899.dkr.ecr.eu-central-1.amazonaws.com
     - sed 's/TAG/$CI_COMMIT_BRANCH$CI_PIPELINE_IID/g' k8s/deployment.yaml | kubectl apply -f -
